# Generated by Django 5.0.3 on 2024-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('empid', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
